include: package:lints/recommended.yaml

analyzer:
  plugins:
    - dart_code_metrics

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - avoid_returning_null_for_future
    - avoid_slow_async_io
    - avoid_type_to_string
    - comment_references
    - join_return_with_assignment
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - prefer_single_quotes
    - unawaited_futures
    - unnecessary_parenthesis
    - unnecessary_statements
    - use_named_constants
    - require_trailing_commas
    - prefer_constructors_over_static_methods
    - prefer_final_locals
    - prefer_final_fields
    - avoid_setters_without_getters
    - sort_unnamed_constructors_first
    - use_enums
    - sort_pub_dependencies

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-methods: 10
    number-of-parameters: 5
    source-lines-of-code: 75
    maintainability-index: 50
  rules:
    - avoid-collection-methods-with-unrelated-types
    - avoid-global-state
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - binary-expression-operand-order
    - member-ordering-extended:
        alphabetize: false
        alphabetize-by-type: false
        order:
          - private-static-const-fields
          - private-static-final-fields
          - private-static-var-fields
          - private-static-late-const-fields
          - private-static-late-final-fields
          - private-static-late-var-fields

          - public-static-const-fields
          - public-static-final-fields
          - public-static-var-fields
          - public-static-late-const-fields
          - public-static-late-final-fields
          - public-static-late-var-fields

          - private-const-fields
          - private-final-fields
          - private-var-fields
          - private-late-const-fields
          - private-late-final-fields
          - private-late-var-fields

          - protected-public-const-fields
          - protected-public-final-fields
          - protected-public-var-fields
          - protected-public-late-const-fields
          - protected-public-late-final-fields
          - protected-public-late-var-fields

          - public-const-fields
          - public-final-fields
          - public-var-fields
          - public-late-const-fields
          - public-late-final-fields
          - public-late-var-fields

          - overridden-public-const-fields
          - overridden-public-final-fields
          - overridden-public-var-fields
          - overridden-public-late-const-fields
          - overridden-public-late-final-fields
          - overridden-public-late-var-fields

          - const-constructors
          - constructors
          - named-constructors
          - factory-constructors

          - protected-getters
          - overriden-getters
          - public-getters
          - getters

          - protected-setters
          - overriden-setters
          - public-setters
          - setters

          - overriden-public-methods
          - public-methods
          - protected-public-methods
          - private-methods

          - public-static-methods
          - protected-static-methods
          - private-static-methods
    - no-boolean-literal-compare
    - no-equal-then-else
    - prefer-commenting-analyzer-ignores
    - prefer-first
    - prefer-immediate-return
    - prefer-last
    - prefer-extracting-callbacks:
        allowed-line-count: 5
